"""create enquiries table

Revision ID: 0f4bdd74c374
Revises: 
Create Date: 2026-07-17 07:26:37.464514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4bdd74c374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_page', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiries_status'))
        batch_op.drop_index(batch_op.f('ix_enquiries_phone'))
        batch_op.drop_index(batch_op.f('ix_enquiries_email'))
        batch_op.drop_index(batch_op.f('ix_enquiries_created_at'))

    op.drop_table('enquiries')
    # ### end Alembic commands ###
