"""Remove pincode from enquiries

Revision ID: bf9146b6b3da
Revises: 0f4bdd74c374
Create Date: 2026-07-18 16:04:08.312452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9146b6b3da'
down_revision = '0f4bdd74c374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('pincode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
